// Copyright Nicholas Reardon

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"


namespace AuraGameplayTags
{
	// Primary Attributes
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_PRIMARY_STRENGTH);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_PRIMARY_INTELLIGENCE);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_PRIMARY_RESILIENCE);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_PRIMARY_VIGOR);

	// Secondary Attributes
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_SECONDARY_ARMOR);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_SECONDARY_ARMORPENETRATION);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_SECONDARY_BLOCKCHANCE);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_SECONDARY_CRITICALHITCHANCE);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_SECONDARY_CRITICALHITDAMAGE);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_SECONDARY_CRITICALHITRESISTANCE);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_SECONDARY_HEALTHREGENERATION);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_SECONDARY_MANAREGENERATION);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_SECONDARY_MAXHEALTH);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_SECONDARY_MAXMANA);
	
	// Vital Attributes
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_VITAL_HEALTH);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ATTRIBUTES_VITAL_MANA);
	
	// Input Tags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUTTAG_LMB);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUTTAG_RMB);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUTTAG_1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUTTAG_2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUTTAG_3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INPUTTAG_4);

}



// /**
//  * AuraGameplayTags
//  *
//  * Singleton contain naitive Gameplay Tags
//  */
// struct FAuraGameplayTags
// {
// public:
// 	static const FAuraGameplayTags& Get() { return GameplayTags; }
// 	static void InitializeNativeGameplayTags();
// protected:
//
// private:
// 	static FAuraGameplayTags GameplayTags;
// };